### ISSUE TITLE
Proxy?

### ISSUE THREAD

**Issue by ghost** [AdobeDocs/dynamic-media-classic.en#1]
This article misses information on how to configure in case users must upload through a proxy.

**Comment by anujkapo** [comment]
Thanks, @SchorschAdobe . I don't see the article link or the .md file that you are referring to. Can you please let us know?

**Comment by ghost** [comment]
Hi Anujkapo,

 

this should be
https://experienceleague.adobe.com/docs/dynamic-media-classic/using/upload-p
ublish/publishing-files.html?lang=en 

 

Best Regards,

 

Georg

 

Georg M. Weinzierl  | Sr. Customer Success Manager  |   T +49 151 24043268 |
***@***.***> ***@***.***

 

 

From: anujkapo ***@***.***> 
Sent: Samstag, 11. Dezember 2021 09:52
To: AdobeDocs/dynamic-media-classic.en
***@***.***>
Cc: Georg Weinzierl ***@***.***>; Mention
***@***.***>
Subject: Re: [AdobeDocs/dynamic-media-classic.en] Proxy? (Issue #1)

 

Thanks, @SchorschAdobe
<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FSchorschAdobe&data=04%7C01%7Cweinzier%40adobe.com%7C3ef52ac8d78d48d9a294
08d9bc837f25%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637748095226389608
%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWw
iLCJXVCI6Mn0%3D%7C3000&sdata=GrNchS8ys07X%2FYR1vLBFvWDJx683sISTX6we3DW0YZg%3
D&reserved=0>  . I don't see the article link or the .md file that you are
referring to. Can you please let us know?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FAdobeDocs%2Fdynamic-media-classic.en%2Fissues%2F1%23issuecomment-9915573
78&data=04%7C01%7Cweinzier%40adobe.com%7C3ef52ac8d78d48d9a29408d9bc837f25%7C
fa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637748095226389608%7CUnknown%7CTW
FpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D
%7C3000&sdata=TFGodt4n59J%2FFa2BN8LMGtkMX8OZ2wFSe45SECHAqig%3D&reserved=0> ,
or unsubscribe
<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fnotifications%2Funsubscribe-auth%2FAQDTGCCBOUAM6A4YMBVZJXTUQMGK7ANCNFSM5
JZFLYTA&data=04%7C01%7Cweinzier%40adobe.com%7C3ef52ac8d78d48d9a29408d9bc837f
25%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637748095226389608%7CUnknown
%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6M
n0%3D%7C3000&sdata=w8wmd5AKGzK6zfCRYlkQ4YvwA8QrAvPHb42%2FtmmOZUw%3D&reserved
=0> .
Triage notifications on the go with GitHub Mobile for iOS
<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.appl
e.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%
26pt%3D524675&data=04%7C01%7Cweinzier%40adobe.com%7C3ef52ac8d78d48d9a29408d9
bc837f25%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637748095226389608%7CU
nknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJ
XVCI6Mn0%3D%7C3000&sdata=z1URKW8Ff93XnNEwcU0TFPhSHKG0lCsG2c2wQyQ9zCk%3D&rese
rved=0>  or Android.
<https://github.com/notifications/beacon/AQDTGCHJ6JFOSFW4T6AIO33UQMGK7A5CNFS
M5JZFLYTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHMM7OAQ
.gif>

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Closing as the associated jira was closed. See CQDOC-18818 for info.
