### ISSUE TITLE
SAM User can not be synchronized 

### ISSUE THREAD

**Issue by ic20b103** [AdobeDocs/dynamic-media-classic.en#2]
Issue in ./help/support.md
Hi team,
I have an issue with adobe experience manager. The issue is, that I can not log in in the cloud and get the error: "SAML-User can not be synchronized".
I alredy did reset my password, did updates etc., but it does not work. Can you please help with the issue? 

![adobe_issue](https://user-images.githubusercontent.com/117016766/204486976-14ba258f-874f-4f6d-ab23-76c10bb7ca14.PNG)

**Comment by aheim0** [comment]
Thanks for contacting us, but this mechanism is only intended for issues with the documentation.

As you require assistance with the software, please contact our Support Team. 

Closing this issue.
