### ISSUE TITLE
User not receive account notification email

### ISSUE THREAD

**Issue by bradfordeurasia** [AdobeDocs/dynamic-media-classic.en#3]
Hi Support 

Only this user adrian.djalali@gmail.com not receive any confirmation E-Mail from Adobe Dynamic Classic  when was created, tryid several times, checked Spam Folder but nothing, please check.

![No_Email](https://github.com/AdobeDocs/dynamic-media-classic.en/assets/12324389/d3861825-c43a-40f3-9f68-0eae3becb83b)

Kind Regards

Nenad Pocuca

E-Commerce Manager - Eurasia
The Bradford Exchange Services Ltd.
Jöchlerweg 2
CH-6340 Baar
Switzerland

 

Phone +41 (0)41 768 58 29

nenad.pocuca@bgeltd.com

[www.bradford.ch](http://www.bradford.ch/)

**Comment by anujkapo** [comment]
Hi @bradfordeurasia. You have followed the process to report an issue in one of the Experience Manager articles available on Experience League. However, you wanted to reach Adobe support team for this issue. I would request you to contact Adobe support. Thanks!

**Comment by guillaumecarlino** [comment]
Closing this issue. As @anujkapo said, this is for documentation issues.
 Please contact Support here: https://experienceleague.adobe.com/home#support
