### ISSUE TITLE
would like to download some of our older images

### ISSUE THREAD

**Issue by kelleyfoust** [AdobeDocs/dynamic-media-classic.en#3]
Issue in ./help/introduction.md
All i have is a list in excel of over 5000 images we need to download.  is there a way to submit a comma delimited list to select for export?

**Comment by bohnertchris** [comment]
Hello @kelleyfoust . Thank you for the issue. This is however a forum for reporting problems with the documentation. If you have a question about how to use Dynamic Media Classic, we encourage you to reach out to our customer care teams or user forums.

https://helpx.adobe.com/contact/enterprise-support.ec.html
https://forums.adobe.com/community/experience-cloud/marketing-cloud/experience-manager
