### ISSUE TITLE
Target Classic was deprecated more than two years ago.

### ISSUE THREAD

**Issue by mtalbot29** [AdobeDocs/dynamic-media-classic.en#5]
Issue in ./help/integrating-scene7-target-classic.md

This topic need to be updated to reflect Target Standard/Premium rather than Classic.

**Comment by rickbrough** [comment]
Mark, you're still in documentation, right? If so, then log a doc issue in Jira and assigned it to me so this issue can be tracked. In the ticket description, add what "Target Classic" should be replaced with.

**Comment by mtalbot29** [comment]
Target Classic should be replaced with Target Standard/Premium. And I'm not sure what else needs to be changed, but there is no such thing as Target Classic. And I can't find a project.
